export const DOG_BREEDS = [
  '',
  'Affenpinscher',
  'Akbash',
  'Akita',
  'American Blue Heeler',
  'Appenzell Mountain Dog',
  'Basenji',
  'Beagle',
  'Beauceron',
  'Berger Picard',
  'Bernese Mountain Dog',
  'Bichon Frise',
  'Black Mouth Cur',
  'Bloodhound',
  'Blue Lacy',
  'Boerboel',
  'Bolognese',
  'Borzoi',
  'Boxer',
  'Brasileiro, Fila',
  'Briard',
  'Buhund, Norwegian',
  'Bulldog',
  'Bulldog, American',
  'Bulldog, English',
  'Bulldog, French',
  'Bulldog, Old English',
  'Bulldog, Victorian',
  'Bullmastiff',
  'Canaan Dog',
  'Canario, Presa',
  'Carolina Dog',
  'Catahoula Leopard Dog',
  'Cattle Dog',
  'Cattle Dog, Australian (Blue Heeler)',
  'Cattle Dog, Australian (Red Heeler)',
  'Chihuahua',
  'Chihuahua, Long Coat',
  'Chihuahua, Short Coat',
  'Chinese Crested Dog',
  'Chinese Shar-Pei',
  'Chow Chow',
  'Cockapoo',
  'Collie',
  'Collie, Bearded',
  'Collie, Border',
  'Collie, Rough',
  'Collie, Smooth',
  'Coonhound',
  'Coonhound, Bluetick',
  'Coonhound, English',
  'Coonhound, Redbone',
  'Coonhound, Treeing Walker',
  'Corgi, Cardigan Welsh',
  'Corgi, Pembroke Welsh',
  'Coton De Tulear',
  'Dachshund',
  'Dachshund, Miniature Long Haired',
  'Dachshund, Miniature Smooth Haired',
  'Dachshund, Miniature Wire Haired',
  'Dachshund, Standard Long Haired',
  'Dachshund, Standard Smooth Haired',
  'Dachshund, Standard Wire Haired',
  'Dalmatian',
  'Dogo Argentino',
  'Dogue de Bordeaux',
  'Elkhound, Norwegian',
  'Entlebucher',
  'Eskimo Dog',
  'Eskimo, American',
  'Feist',
  'Flanders, Bouvier Des',
  'Foxhound, American',
  'Foxhound, English',
  'Great Dane',
  'Greater Swiss Mountain Dog',
  'Greyhound',
  'Greyhound, Italian',
  'Griffon, Brussels',
  'Griffon, Petit Basset Vendeen',
  'Griffon, Wire-Haired Pointing',
  'Havanese',
  'Hound',
  'Hound, Afghan',
  'Hound, Basset',
  'Hound, Black and Tan Coonhound',
  'Hound, Bloodhound',
  'Hound, Halden (Haldenstover)',
  'Hound, Ibizan',
  'Hound, Irish Wolfhound',
  'Hound, Pharaoh',
  'Hound, Plott',
  'Hound, Scottish Deerhound',
  'Husky',
  'Husky, Alaskan',
  'Husky, Siberian',
  'Japanese Chin',
  'Kai Dog',
  'Karelian Bear Dog',
  'Keeshond',
  'Kelpie, Australian',
  'Klee Kai',
  'Komondor',
  'Korean Jindo',
  'Kuvasz',
  'Lapphund, Finnish',
  'Leonberger',
  'Lhasa Apso',
  'Lowchen',
  'Lundehund, Norwegian',
  'Malamute, Alaskan',
  'Malinois, Belgian',
  'Maltese',
  'Mastiff',
  'Mastiff, Bullmastiff',
  'Mastiff, Cane Corso',
  'Mastiff, Neapolitan',
  'Mastiff, Tibetan',
  'Mixed Breed (Large)',
  'Mixed Breed (Medium) ',
  'Mixed Breed (Small)',
  'Mountain Cur',
  'Mountain Dog',
  'Newfoundland',
  'Norbottenspets',
  'Nureongi',
  'Otterhound',
  'Papillon',
  'Pei, Shar',
  'Pekingese',
  'Pinscher, Austrian',
  'Pinscher, Doberman',
  'Pinscher, German',
  'Pinscher, Miniature',
  'Pointer',
  'Pointer, English',
  'Pointer, German Shorthaired',
  'Pointer, German Wirehaired',
  'Pomeranian',
  'Poodle',
  'Poodle, Miniature',
  'Poodle, Standard',
  'Poodle, Toy',
  'Portugese Water Dog',
  'Pug',
  'Puli',
  'Pyrenees, Great',
  'Queensland Heeler',
  'Retriever',
  'Retriever, Black Labrador',
  'Retriever, Chesapeake Bay',
  'Retriever, Chocolate Labrador',
  'Retriever, Curly-Coated',
  'Retriever, Flat-Coated',
  'Retriever, Golden',
  'Retriever, Labrador',
  'Retriever, Nova Scotia Duck-Tolling',
  'Retriever, Yellow Labrador',
  'Ridgeback, Rhodesian',
  'Ridgeback, Thai',
  'Rottweiler',
  'Saint Bernard',
  'Saluki',
  'Samoyed',
  'Schipperke',
  'Schnauzer',
  'Schnauzer, Giant',
  'Schnauzer, Miniature',
  'Schnauzer, Standard',
  'Setter',
  'Setter, English',
  'Setter, Gordon',
  'Setter, Irish',
  'Sheep Dog',
  'Sheepdog, Caucasian Ovtcharka',
  'Sheepdog, Mcnab',
  'Sheepdog, Old English',
  'Sheepdog, Polish Lowland',
  'Sheepdog, Shetland',
  'Shepherd',
  'Shepherd, Anatolian',
  'Shepherd, Australian',
  'Shepherd, Belgian Malinois',
  'Shepherd, Belgian Sheepdog',
  'Shepherd, Belgian Tervuren',
  'Shepherd, Dutch',
  'Shepherd, English',
  'Shepherd, German',
  'Shepherd, German King',
  'Shepherd, White German',
  'Shiba Inu',
  'Shih Tzu',
  'Sloughi',
  'Spaniel',
  'Spaniel, American Cocker',
  'Spaniel, American Water',
  'Spaniel, Brittany',
  'Spaniel, Cavalier King Charles',
  'Spaniel, Clumber',
  'Spaniel, Cocker',
  'Spaniel, English Cocker',
  'Spaniel, English Springer',
  'Spaniel, English Toy',
  'Spaniel, Irish Water',
  'Spaniel, Sussex',
  'Spaniel, Tibetan',
  'Spaniel, Welsh Springer',
  'Spinone, Italian',
  'Spitz',
  'Spitz, Finnish',
  'Spitz, German',
  'Taiwanese Mountain Dog',
  'Terrier',
  'Terrier, Airedale',
  'Terrier, American Hairless',
  'Terrier, American Pit Bull',
  'Terrier, American Staffordshire',
  'Terrier, Australian',
  'Terrier, Bedlington',
  'Terrier, Black Russian',
  'Terrier, Border',
  'Terrier, Boston',
  'Terrier, Bull',
  'Terrier, Cairn',
  'Terrier, Dandi Dinmont',
  'Terrier, Fox',
  'Terrier, Fox, Smooth',
  'Terrier, Glen of Imaal',
  'Terrier, Irish',
  'Terrier, Jack Russell',
  'Terrier, Kerry Blue',
  'Terrier, Lakeland',
  'Terrier, Manchester',
  'Terrier, Norfolk',
  'Terrier, Norwich',
  'Terrier, Parson Jack Russell',
  'Terrier, Patterdale (Fell)',
  'Terrier, Pit Bull',
  'Terrier, Rat',
  'Terrier, Scottish Scottie',
  'Terrier, Sealyham',
  'Terrier, Silky',
  'Terrier, Skye',
  'Terrier, Smooth Fox',
  'Terrier, Soft Coated Wheaten',
  'Terrier, Staffordshire Bull',
  'Terrier, Tibetan',
  'Terrier, Toy Fox',
  'Terrier, Welsh',
  'Terrier, West Highland White Westie',
  'Terrier, Wheaten',
  'Terrier, Wire Fox',
  'Terrier, Wirehaired',
  'Terrier, Yorkshire, Yorkie',
  'Unknown',
  'Vallhund, Swedish',
  'Vizsla',
  'Vizsla, Smooth Haired',
  'Water Dog, Portuguese',
  'Weimaraner',
  'Whippet',
  'Wolfhound, Irish',
  'Xoloitzcuintle (Mexican Hairless)'
];


export const CAT_BREEDS = [
  '',
  'Domestic Shorthair',
  'Abyssinian',
  'American Bobtail',
  'American Curl',
  'American Shorthair',
  'American Wirehair',
  'Balinese',
  'Bengal',
  'Birman',
  'Bombay',
  'British Shorthair',
  'Burmese',
  'Chartreux',
  'Colorpoint Shorthair',
  'Cornish Rex',
  'Cymric',
  'Devon Rex',
  'Domestic Longhair',
  'Domestic Medium Hair',
  'Egyptian Mau',
  'Exotic Longhair',
  'Exotic Shorthair',
  'Extra-Toes Cat (Hemingway Polydactyl)',
  'Havana Brown',
  'Himalayan',
  'Japanese Bobtail',
  'Javanese',
  'Korat',
  'LaPerm',
  'Maine Coon',
  'Manx',
  'Munchkin',
  'Nebelung',
  'Norwegian Forest Cat',
  'Ocicat',
  'Oriental Long Hair',
  'Oriental Short Hair',
  'Persian',
  'Pixie-Bob',
  'Ragamuffin',
  'Ragdoll',
  'Russian Blue',
  'Scottish Fold',
  'Selkirk Rex',
  'Siamese',
  'Siberian',
  'Singapura',
  'Snowshoe',
  'Somali',
  'Sphynx',
  'Tonkinese',
  'Turkish Angora',
  'Turkish Van',
  'Unknown'
];


export const DOG_COLORS = [
  '',
  'Apricot',
  'Beige',
  'Black',
  'Blond',
  'Blue',
  'Blue Black',
  'Brindle',
  'Brown',
  'Chocolate',
  'Cream',
  'Fawn',
  'Golden',
  'Grey',
  'Red/Mahogany',
  'Sable',
  'Sandy',
  'Silver',
  'Tan',
  'Wheaten',
  'White',
  'Yellow'
];


export const CAT_COLORS = [
  '',
  'Albino',
  'Apricot',
  'Black',
  'Blonde',
  'Blue Black',
  'Blue',
  'Brown',
  'Buff',
  'Calico',
  'Charcoal',
  'Chocolate',
  'Copper',
  'Cream',
  'Ebony',
  'Fawn',
  'Flame',
  'Grey',
  'Lilac',
  'Liver',
  'Lynx',
  'Mahogany',
  'Orange',
  'Red',
  'Ruddy',
  'Rust',
  'Sable',
  'Salt & Pepper',
  'Seal',
  'Shaded Blue Cream Cameo',
  'Silver Black',
  'Silver',
  'Smoke',
  'Tan',
  'Torbie',
  'Tortoise',
  'Wheaten',
  'White',
  'Yellow'
];


export const DOG_PATTERNS = [
  '',
  'Badger',
  'Bicolor',
  'Brindle',
  'Harlequin',
  'Merle',
  'Salt and Pepper',
  'Solid',
  'Spotted',
  'Tick',
  'Tricolor'
];


export const CAT_PATTERNS = [
  '',
  'Agouti',
  'Calico',
  'Dapple',
  'Dilute',
  'Merle',
  'Point',
  'Tabby',
  'Torbie',
  'Tortie',
  'Tuxedo',
  'Van'
];

export const RABIES_PRODUCT_MANUFACTURER: {
  product: string;
  manufacturer: string;
}[] = [
  { product: 'Rabvac 1', manufacturer: 'Elanco' },
  { product: 'Rabvac 3', manufacturer: 'Elanco' },

  { product: 'Vanguard Rabies 1 year', manufacturer: 'Zoetis' },
  { product: 'Vanguard Rabies 3 year', manufacturer: 'Zoetis' },

  { product: 'Nobivac 1-Rabies', manufacturer: 'Zoetis/Merck' },
  { product: 'Nobivac 3-Rabies', manufacturer: 'Zoetis/Merck' },
  { product: 'Nobivac 3-Rabies CA', manufacturer: 'Merck' },

  { product: 'IMRAB 1 (Merial)', manufacturer: 'Merial' },
  { product: 'IMRAB 3 (Merial)', manufacturer: 'Merial' },

  { product: 'PUREVAX Feline Rabies (Merial)', manufacturer: 'Merial' },
  { product: 'PUREVAX Feline Rabies 3 Yr (Merial)', manufacturer: 'Merial' },
  { product: 'PUREVAX Feline 3/Rabies (Merial)', manufacturer: 'Merial' },
  { product: 'PUREVAX Feline 4/Rabies (Merial)', manufacturer: 'Merial' },

  { product: 'Rabies (generic)', manufacturer: 'None' },

  { product: 'Rabdomun 3', manufacturer: 'Merck' },
  { product: 'Rabdomun 1', manufacturer: 'Merck' },

  { product: 'IMRAB 3 TF (Merial)', manufacturer: 'Merial' },
  { product: 'IMRAB 1 TF (Merial)', manufacturer: 'Merial' },

  { product: 'Rabies 3-year (generic)', manufacturer: 'None' },
  { product: 'Rabisin', manufacturer: 'Elanco' },

  { product: 'IMRAB Large Animal Rabies (Merial)', manufacturer: 'Merial' },
  { product: 'Rabies - Equine (generic)', manufacturer: 'None' },
  { product: 'EquiRab with Havlogen', manufacturer: 'Merck' },

  { product: 'PUREVAX Feline Rabies', manufacturer: 'Boehringer Ingelheim' },
  { product: 'PUREVAX Feline Rabies 3 Yr', manufacturer: 'Boehringer Ingelheim' },
  { product: 'PUREVAX Feline 3/Rabies', manufacturer: 'Boehringer Ingelheim' },
  { product: 'PUREVAX Feline 4/Rabies', manufacturer: 'Boehringer Ingelheim' },

  { product: 'IMRAB 1', manufacturer: 'Boehringer Ingelheim' },
  { product: 'IMRAB 3', manufacturer: 'Boehringer Ingelheim' },
  { product: 'IMRAB 3 TF', manufacturer: 'Boehringer Ingelheim' },
  { product: 'IMRAB 1 TF', manufacturer: 'Boehringer Ingelheim' },
  { product: 'IMRAB Large Animal Rabies', manufacturer: 'Boehringer Ingelheim' },

  { product: 'IMRAB + Potomavac', manufacturer: 'Boehringer Ingelheim' }
];